export { default as ANavBar } from './ANavbar'
export { default as BBanner } from './BBanner'
export { default as CTop } from './CTop'
export { default as DRecipes } from './DRecipes'
export { default as EProducts } from './EProducts'
export { default as GFooter } from './GFooter'
export { default as Layout } from './Layout'