import Head from 'next/head'
import { ANavBar, BBanner, CTop, DRecipes, EProducts, FTips, GFooter } from '../components'

const recipeElements = [
  {
    datePublished: "March 15, 2023",
    category: "Recipes",
    title: "Colourful Salad"
  },
  {
    datePublished: "March 15, 2023",
    category: "Recipes",
    title: "Best Vegan Pizza"
  },
  {
    datePublished: "March 15, 2023",
    category: "Recipes",
    title: "Dutch Oven Bread"
  }
]

const productElements = [
  {
    datePublished: "March 15, 2023",
    category: "Product Reviews",
    title: "Peeler"
  },
  {
    datePublished: "March 15, 2023",
    category: "Product Reviews",
    title: "KitchenAid Mixer"
  },
  {
    datePublished: "March 15, 2023",
    category: "Product Reviews",
    title: "Dutch Oven"
  },
]



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <ANavBar 
        
        />
      </div>

      <div>
        {recipeElements.map((content) => (
          <DRecipes 
            datePublished={content.datePublished}
            category={content.category}
            title={content.title}
          />
        ))}
      </div>

      <div>
        {productElements.map((content) => (
          <EProducts 
            datePublished={content.datePublished}
            category={content.category}
            title={content.title}
          />
        ))}
      </div>
    </>
  )
}
